;;; Generated by Guile-SMC

(define-module
  (ini fsm)
  #:use-module
  (oop goops)
  #:use-module
  (smc fsm)
  #:export
  (<ini-fsm>))


(define %transition-table
  `((read_section_property_key
      (,guard:eof-object? ,action:no-op #f)
      (,guard:equals-sign?
       ,action:update-stanza
       read_section_property_value)
      (,#{guard:#t}#
       ,action:store
       read_section_property_key))
    (read_property_key
      (,guard:eof-object? ,action:syntax-error #f)
      (,guard:equals-sign?
       ,action:update-stanza
       read_property_value)
      (,#{guard:#t}# ,action:store read_property_key))
    (read_section_title
      (,guard:eof-object? ,action:no-op #f)
      (,guard:right-square-bracket?
       ,action:start-section
       read_section_content)
      (,#{guard:#t}# ,action:store read_section_title))
    (read (,guard:eof-object? ,action:no-op #f)
          (,guard:semicolon?
           ,action:no-op
           skip_global_comment)
          (,guard:left-square-bracket?
           ,action:no-op
           read_section_title)
          (,guard:letter? ,action:store read_property_key)
          (,#{guard:#t}# ,action:no-op read))
    (read_section_property_value
      (,guard:eof-object? ,action:no-op #f)
      (,guard:newline?
       ,action:append-property
       read_section_content)
      (,#{guard:#t}#
       ,action:store
       read_section_property_value))
    (read_section_content
      (,guard:semicolon? ,action:no-op skip_comment)
      (,guard:letter?
       ,action:store
       read_section_property_key)
      (,guard:left-square-bracket?
       ,action:no-op
       read_section_title)
      (,#{guard:#t}#
       ,action:no-op
       read_section_content))
    (skip_comment
      (,guard:eof-object? ,action:no-op #f)
      (,guard:newline?
       ,action:no-op
       read_section_content)
      (,#{guard:#t}# ,action:no-op skip_comment))
    (read_property_value
      (,guard:eof-object? ,action:syntax-error #f)
      (,guard:newline? ,action:append-property read)
      (,#{guard:#t}# ,action:store read_property_value))
    (skip_global_comment
      (,guard:newline? ,action:no-op read)
      (,#{guard:#t}# ,action:no-op skip_global_comment))))

(define-class <ini-fsm> (<fsm>))

(define-method
  (initialize (self <ini-fsm>) initargs)
  (fsm-transition-table-set!
    self
    (transition-list->hash-table %transition-table))
  (fsm-current-state-set!
    self
    (fsm-state self read)))

